plugins {
  id('java-common-conventions')
  id('maven-publish-conventions')
}

description = 'JUnit 5 integration that adapts a TestTemplate suite into JUnit 5 dynamic tests via JUnitTestSuiteFactory.'

dependencies {
  api libs.junit.api

  implementation project(':testtemplate-api')

  compileOnly libs.jspecify

//  testImplementation project(':testtemplate-core')

  testImplementation libs.assertj
  testImplementation libs.junit
  testImplementation libs.logback

  testCompileOnly libs.jspecify

  testRuntimeOnly libs.junit.runtime
}
