plugins {
  id('java-common-conventions')
  id('maven-publish-conventions')
}

description = 'Optional extension integrating Mockito mocks into TestTemplate via MockitoExtension, with automatic setup and verification lifecycle.'

dependencies {
  implementation project(':testtemplate-api')

  implementation libs.mockito.core
  implementation libs.slf4j.api

  compileOnly libs.jspecify

  testImplementation libs.assertj
  testImplementation libs.junit
  testImplementation libs.mockito.junit

  testCompileOnly libs.jspecify

  testRuntimeOnly libs.junit.runtime
}
