plugins {
  id 'java-library'
  id 'checkstyle'
  id 'jacoco'
  id 'org.shipkit.shipkit-auto-version'
}

group = 'io.github.testtemplate'

//repositories {
//  mavenCentral()
//}

java {
  toolchain {
    languageVersion = JavaLanguageVersion.of(21)
  }
}

test {
  useJUnitPlatform()

  testLogging {
    events = ['FAILED', 'PASSED', 'SKIPPED']
  }

  finalizedBy(jacocoTestReport)
}

checkstyle {
  toolVersion = libs.versions.checkstyle.get()
}

jacocoTestReport {
    reports {
        xml.required = true
        html.required = false
        csv.required = false
    }
}
