plugins {
  id('java-common-conventions')
  id('maven-publish-conventions')
}

dependencies {
  api project(':testtemplate-api')

  implementation project(':testtemplate-core')
  implementation project(':testtemplate-junit')

  implementation libs.yaml

  compileOnly project(':testtemplate-extension-json')
  compileOnly project(':testtemplate-extension-mockito')

  compileOnly libs.jspecify

  testImplementation libs.assertj
  testImplementation libs.junit

  testCompileOnly libs.jspecify

  testRuntimeOnly libs.junit.runtime
}
