plugins {
  id('java-common-conventions')
  id('maven-publish-conventions')
}

description = 'Optional extension adding JSONPath-powered variable support to TestTemplate via JsonExtension.'

dependencies {
  implementation project(':testtemplate-api')

  implementation libs.json.path
  implementation libs.slf4j.api

  compileOnly libs.jspecify

  testImplementation libs.assertj
  testImplementation libs.junit
  testImplementation libs.mockito.junit

  testCompileOnly libs.jspecify

  testRuntimeOnly libs.junit.runtime
}
